### ISSUE TITLE
Client should freak out less if you don't have the mod installed

### ISSUE THREAD

**Issue by Hyphen-ated** [Zamiell/isaac-racing-client#5]
If you launch the client without the mod installed, it pops up this dialog
> Error
Failed to find the Racing+ mod in your mods directory. Are you sure that you subscribed to it on the Steam Workshop? If you did, double check your mods directory to make sure that Steam actually downloaded it. For more information, see the download instructions at: https://isaacracing.net/download
Exit and relaunch

and prevents you from doing anything at all, like using the chat, or viewing who is currently racing. (the reason I launched the client is I wanted to look at currently active races.)

I don't see a good reason why not having the mod installed at a given moment should stop you from using features of the client that don't depend on you running the game.

it even taunts you by showing the normal UI for a split second before taking it away to show the dialog

**Comment by Zamiell** [comment]
To be robust, Racing+ needs to perform a number of checks before it lets you race, including:

1) Do you have at least 1 1,000,000% save file?
2) Do you have the Racing+ mod installed?
3) Do you have any other mods than the Racing+ mod enabled?
4) Is "ModsEnabled" equal to 1 in your options.ini file?

Since doing these are expensive (in terms of time), I made them occur upon login. Alternatively, I could make a global variable "checksCompleted", and then make the checks occur upon joining the first race, and then set "checksCompleted" to true.

However, there are some disadvantages of doing it that way:

1) The user might have to wait some extra seconds before they can join or create their first race, which is annoying.
2) If someone is waiting around for an opponent, then finally gets one, and then creates a race, and their configuration / mod settings messed up, now the other person is delayed. This seems less smoother than the current way, in which players forced to get everything squared away before actually asking other people to race.

**Comment by Zamiell** [comment]
In the long term, I'd like to set up the ability to "spectate" races from a web GUI that continuously polls a server API via either AJAX or websockets. I'd love help on programming/implementing this.

**Comment by Hyphen-ated** [comment]
> Alternatively, I could make a global variable "checksCompleted", and then make the checks occur upon joining the first race, and then set "checksCompleted" to true.

why not do the checks on launch and make the penalty be "you can't create/join a race" rather than "you can't use the client at all"

like basically just add a button to dismiss the existing dialog that says something like "Okay, I'll do that later"

**Comment by Zamiell** [comment]
That sounds reasonable. I'll accept a pull request that implements that.

**Comment by Zamiell** [comment]
Racing+ no longer checks to see that the mod is installed. Still need to add a check to see if Racing+ mod is installed before allowing someone to ready up.

**Comment by Zamiell** [comment]
Check implemented in v0.11.4.
